### ISSUE TITLE
Consider removing functor instance from Store

### ISSUE THREAD

**Issue by felixSchl** [coot/purescript-redox#1]
I was very surprised to see this: https://github.com/coot/purescript-redox/blob/1bd8ca60c938632f940183c0803f112eb4667e58/src/Redox/Free.purs#L49-L50 as this clearly violates the functor laws. Maybe calling `mapStore` directly (or call it `modifyStore`) might be better, what do you think? I just double checked and even purescript-refs defines no functor instance for it's Ref type.

**Comment by coot** [comment]
Your're right, it's effectful so it shouldn't be a functor.
