### ISSUE TITLE
What is the use of "DSL (State -> State)"

### ISSUE THREAD

**Issue by felixSchl** [coot/purescript-redox#3]
As far as I can tell, the new state value that gets produced by this does not get emitted in subscriptions and the state does not update with it. What is the intended use case for this if it has no impact on the state or store subscriptions? All tests use `pure id`

**Comment by coot** [comment]
That's actually a side effect of [pairing free and coffee](https://github.com/coot/purescript-redox/blob/master/test/Free.purs#L81) within exploreM.

The [dispatch](https://github.com/coot/purescript-redox/blob/master/src/Redox/Free.purs#L39) will actually update the state, though if you use dispatchP and you build an interpreter with [mkIncInterp](https://github.com/coot/purescript-redox/blob/master/src/Redox/Utils.purs#L44) and [runSubscriptions](https://github.com/coot/purescript-redox/blob/master/src/Redox/Utils.purs#L56) that will be the case.
