### ISSUE TITLE
Multi-step async flow example

### ISSUE THREAD

**Issue by spicydonuts** [coot/purescript-redox#7]
Hey, thanks for all the awesome purescript-react related work!

I've looked through the docs/examples here as well as the purescript-dsl-example project, but I'm not really sure how to extend this to something async.  Not just one step in Aff.. more of a multi-step Aff which updates state a few times along the way.

For example, my state allows for `Empty`, `Loading`, `Failed Errors`, or `Ready Data`.  I have the basics working where an action goes all the way from `Empty` to `Ready Data`, but I'm not sure how to model the `Loading` state.  I'm also not really sure how to structure the actions.. maybe I only need one `FetchData` action and the rest can live in the interpreter, or maybe I need separate `FetchDataStart` and `FetchDataEnd` actions.

Does that make sense?

I'm in over my head a little bit with the Cofree stuff, though I think I get Free.. maybe this is obvious and that's all my confusion is coming from 🙂

**Comment by coot** [comment]
In the `Utils` module you have `mkIncInterp`. Pług it in and now a every level of free your store will be updated. But it will not run subscriptions, for that you will also need to add `utils.runSubscriptions`.

What I tend to do is to have one action that takes a `Setter` lens and a value to set something on the   state, then some computations in Free might require that you need to get something from the state to make it available in the free monad: for that I define additional action that takes a `Getter` plus application specific actions like requests, routing (useful in some scenarios), etc.

**Comment by spicydonuts** [comment]
Oh, hmm 🤔  I'll see what I can do, thanks!

**Comment by spicydonuts** [comment]
What's the significance of ending a command with `pure id`?  It seems to behave the same without it.

**Comment by coot** [comment]
That's a consequence of pairing. If you have a non trivial function it will modify the state, if I am not mistaken.

**Comment by spicydonuts** [comment]
Ok, I think that makes sense.. sorry this is going so slow, I appreciate the help.  I tried using an action called `FetchPolicies` and changed the last line:

```purescript
fetchPolicies :: ActionDSL (AppState -> AppState)
fetchPolicies = do
  liftF $ FetchPolicies unit
  pure \s -> s { policies = Loading }
```

This does update the state, but not how I would expect.  The subscribed component goes from "Empty" -> "Loading" and the logger prints a new state containing "Ready Data".  I do have `mkIncInterp` and `runSubscriptions` hooked up, so I tried moving that state update up above the action, but I'm not sure how to make that work.  It seems only the last line can return the new state.

**Comment by spicydonuts** [comment]
Here's the `mkInterp` handler for this action:

```purescript
    fetchPolicies :: AppState -> Aff (ajax :: AJAX | eff) AppState
    fetchPolicies state_ = do
      p <- Policy.fetchPolicies
      pure state_ { policies = either Failed Ready $ runExcept p }
```

And my `runAction` machinery:

```purescript
runAction :: forall eff. ActionDSL (AppState -> AppState) -> AppState-> Aff (ajax :: AJAX | eff) AppState
runAction cmds state = exploreM pair cmds $ reduceMachine state
  where reduceMachine = runSubscriptions store <<< logger <<< mkIncInterp store <<< mkInterp
```

**Comment by spicydonuts** [comment]
Is this even the right way to approach this?  Or should the first action just be sequencing other actions which actually update the state in `mkInterp`?  I'm not sure I understand the purpose of the functions in the actions file.

**Comment by coot** [comment]
Ad first comment: probably the logger runs before the function is applied.  I'd actually prefer to remove this feature, but I havent figured out how to pair without it.

It's better to read the state from the `Store` in actions rather than depend on the state which is passed to `runAction`.  You can use `Redox.Store.getState` for that.

**Comment by spicydonuts** [comment]
I tried sliding the logger to a few different positions in that chain but it didn't seem to change what was logged.

Now I have `interp.fetchPolicies` looking like this:

```purescript
    fetchPolicies :: Aff (StoreEffects e eff) AppState
    fetchPolicies = do
      p <- Policy.fetchPolicies
      st <- getState store
      pure case st.route of
        Policies -> st { policies = either Failed Ready $ runExcept p }
        _ -> st
```

and the action looking like this:

```purescript
fetchPolicies :: ActionDSL (AppState -> AppState)
fetchPolicies = do
  liftF $ FetchPolicies unit
  pure \s -> s { policies = Loading }
```

but it behaves the same.  The state logged to the console is "Ready Data" and the UI shows "Loading".

**Comment by spicydonuts** [comment]
One thing that's interesting.. it now appears as thought the UI changes to "Loading" well before the state is logged in the console, but the UI doesn't see that update.

**Comment by coot** [comment]
Does it run fine if you do `pure id` at the end of `fetchPolicies` and move the update to another action?

**Comment by spicydonuts** [comment]
It works, but doesn't have the intermediate update to indicate loading.  What do you mean by "move the update to another action"?

**Comment by coot** [comment]
Sorry I wasn't precise enough.  That's expected that the final update through `pure \s -> s { policies = Loading }` will not be logged.  It will create the leaf of the Free monad, and the logger runs after every branch.  Take a look at `explore` (`exploreM` is the same):
```
explore
  :: forall f g a b
   . Functor f
  => Functor g
  => (forall x y. f (x -> y) -> g x -> y)
  -> Free f (a -> b)
  -> Cofree g a
  -> b
explore pair m w =
    case runState (runFreeM step m) w of
      Tuple f cof -> f (extract cof)
  where
    step :: f (Free f (a -> b)) -> State (Cofree g a) (Free f (a -> b))
    step ff = state \cof -> pair (map Tuple ff) (tail cof)
```
The `f` in `Tuple f cof` is your final `\s -> s { policies = Loading }`.  I think this should be clear now that nothing gets logged after it.  Consider just `pure f :: Free ActionDSL (ActionDLS -> ActionDSL)`, then  `runFreeM` maps it to `pure f :: State (Cofree ...) (Free ...)`.

Another way to view this is that the `exploreM` pairs branches of the two trees `Free` and `Cofree`,  but `Cofree` does not have leaves so the leaves of `Free` cannot be matched to anything.

**Comment by spicydonuts** [comment]
Ok, I think that makes sense for the logging bit.  Do you have any suggestions or existing examples for modeling that domain logic?  Either how I could get the "Loading" -> "Ready" state change to happen after the "Empty" -> "Loading" change, or alternatively how a single action could trigger additional actions?  It seems like I'd want to describe those steps in a `Free Action ?` DSL so that business logic can be tested in isolation, but I don't know how that maps to Cofree and the interp stuff.. something like:

```purescript
fetchPolicies :: ?
fetchPolicies = do
  SetLoadingState -- is this an action or function?
  policies <- FetchPolicies
  case policies of
    Left err -> SetErrorState err
    Right policies' -> SetReadyState policies'
```

**Comment by coot** [comment]
Just define your dsl as a sum type and build more  complex actions from them composing them in Free. Like in tests or the purecript-dsl-example.

**Comment by spicydonuts** [comment]
Ok, I tried really hard but I'm still missing something.  I've got an action DSL which is nice and everything basically works, but I can't get that intermediate loading state to show up..

Here's the action stuff:

```purescript
setPoliciesState :: Resource (Array Policy) -> ActionDSL (AppState -> AppState)
setPoliciesState policies = liftF $ SetPoliciesState policies id

fetchPolicies' :: ActionDSL (Resource (Array Policy))
fetchPolicies' = do
  policiesR <- liftF $ FetchPolicies id
  pure $ either Failed (Ready <<< sort) policiesR

fetchPolicies :: ActionDSL (AppState -> AppState)
fetchPolicies = do
  _ <- setPoliciesState Loading
  policies <- fetchPolicies'
  setPoliciesState policies
```
pair :: ∀ x y eff. Action (x -> y) -> Run eff x -> Aff eff y
pair (ChangeRoute route f) (Run interp) = f <$> spy <$> interp.changeRoute route
pair (SetPoliciesState policies f) (Run interp) = f <$> spy <$> interp.setPoliciesState policies
pair (FetchPolicies f) (Run interp) = (\{ policies, state } -> f policies state) <$> spy <$> interp.fetchPolicies
And here's pair:

```purescript

```

And here's what gets logged by those `spy` calls:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/715921/30941968-50ec3b50-a3a5-11e7-9195-f3252d399657.png">

It _is_ setting the "policies" property to Loading, but something instantly sets it back to Empty..

**Comment by spicydonuts** [comment]
The UI never reflects that loading state.  A `spy` in render shows it running 3 times, with states Empty, Empty, and Ready.  I don't get why one of those Empty's isn't Loading.  And (maybe a different issue) it seems like it should be skipping that 2nd render of Empty..

**Comment by coot** [comment]
I think you are looking for `Redox.Utils.runSubscriptions` or do that when manually when needed inside your interpreter.

**Comment by spicydonuts** [comment]
I have that: `runAction cmds state = exploreM pair cmds $ (runSubscriptions store <<< mkIncInterp store <<< mkInterp) state`

**Comment by coot** [comment]
Do you have the code somewhere, I can have a look tomorrow.

**Comment by spicydonuts** [comment]
No, it's in an internal project, but I'll try to extract something that reproduces it.  Thanks!

**Comment by spicydonuts** [comment]
Ok, this should do it: https://github.com/spicydonuts/redox-issue

**Comment by spicydonuts** [comment]
Oh yes, steps to run: `yarn` or `npm i`, `pulp build`, `yarn start` (use pulp watch or pscid or an editor plugin to do incremental builds).

In creating this stripped down version I noticed something interesting.  There are some calls to `delay` in `App.Domain.User`.. without those the UI never updates even though the state seems to.  Race condition where only the first of a series of actions is applied?

**Comment by spicydonuts** [comment]
And thanks for taking a look!

**Comment by spicydonuts** [comment]
Not related, but I just noticed `Redox.Utils.compose` is not used or exported

**Comment by coot** [comment]
There are two issues:
* [here] you need to update the state of the user.  You might add another case for that.
There is another issue with updating the view, but I didn't had time to look into it.

**Comment by spicydonuts** [comment]
Ah, yes, the first is definitely an issue but doesn't effect the Users route.  The 2nd I've tried both ways, didn't seem to make a difference in logging, state updates, or the spy calls I placed in both interp and render.

**Comment by spicydonuts** [comment]
To clarify, the render issue remains but I fixed the two you mentioned.  I've been wandering through the redox and react-redox code but I haven't found anything.

**Comment by spicydonuts** [comment]
Found it! 😄 

Actions dispatched during a render don't make it back into React.  I changed `runAction` and everything started working:

```purescript
runAction :: ∀ e eff
   . ActionDSL (AppState -> AppState)
  -> AppState
  -> Aff (AppEffects eff) AppState
runAction cmds state = do
  delay (wrap 0.0)
  exploreM pair cmds $ (addLogger unsafeCoerce <<< runSubscriptions store <<< mkIncInterp store <<< mkInterp) state
```

**Comment by coot** [comment]
Indeed I found an issue in the `react-redox`.  Now the changes that are dispatched between `getInitialState` and `componentDidMount` will be taken into account.

You shouldn't use `mkStoreGlobal` use `mkStore`.  Then you can be sure that only one store is around and you will get redox effects in the top level effects.

**Comment by spicydonuts** [comment]
Ok, thank you!

**Comment by spicydonuts** [comment]
How do you build and share references to `runAction` if the store is not global?

**Comment by coot** [comment]
I just updated the [example](https://github.com/coot/purescript-redox/tree/master/examples/todomvc).

**Comment by spicydonuts** [comment]
I updated to the patterns in the example, using `getState` in `mkInterp` instead of passing it in and creating the store in the root component.  The render issue is back.. just wanted to check my store setup with you in case something is wrong.  The only difference from your example is the dispatch function definition:

```purescript
  store <- mkStore initialState
  interp <- mkInterp store
  withStore store
    (Redox.dispatch (error <<< show) (runAction $ (addLogger unsafeCoerce) (mkIncInterp store interp)))
    container
```

I tried both with and without the `delay` in `runAction`, which fixed it before when I was using the global store.  I also tried on both `react-redox` `2.0.0` and `2.0.1`.

**Comment by spicydonuts** [comment]
Huh.. actually, it _only_ works with `runAction interp cmds state = delay (wrap 0.0) *> exploreM pair cmds interp`.  Using `mkIncInterp` doesn't change the behavior at all.  If I use `delay` the app works but skips rendering that loading state (though it is logged correctly).  If I don't use `delay` nothing renders (this is because my container component on mount is determining the current route from the page url, so that action has to trigger a render for anything else to happen).

**Comment by coot** [comment]
I am not sure if I understand it correctly.  You need to add `runSubscriptions` after `mkIncInterp` or trigger them directly in side your interpreter.

**Comment by spicydonuts** [comment]
!! thank you, overlooked `runSubscriptions` when moving the logic.  I do still need the `delay` call in there, but with that it's all working again.

**Comment by coot** [comment]
Checkout [loading](https://github.com/coot/redox-issue/tree/loading) branch.   I had to change some actions because there were not updating the store and also the `EditUser` component to show loading state.  Now I can see `loading...` in both: `Users` and `EditUser` components.

**Comment by spicydonuts** [comment]
I'm not seeing a difference, other than pointing to `react-redox#master`.  Is there something different there?

**Comment by spicydonuts** [comment]
*a difference to what I have now

**Comment by coot** [comment]
https://github.com/coot/redox-issue/commit/7bbd8042556c09860ce8af669813204bb390b711

**Comment by spicydonuts** [comment]
Yeah, I looked through all the changes.  I don't see a difference other than pointing to that master branch.  I tried doing that as well but I'm not getting it to work at all now.  Both with and without `delay` it isn't re-rendering after the first dispatch in `componentDidMount`.

**Comment by coot** [comment]
Are you using the master branch of `redox`? Have you checked the [interpreter](https://github.com/coot/redox-issue/commit/7bbd8042556c09860ce8af669813204bb390b711#diff-ccf85a9968c5bf655f475750fb2ae914)?

**Comment by spicydonuts** [comment]
No, just master for `react-redox`, matching what's in that branch.  And yes, it's the same except the first line which looks like the other example: https://github.com/coot/purescript-redox/blob/master/examples/todomvc/src/Store.purs#L43

**Comment by coot** [comment]
I ment `react-refox#master`. Hmm, I have no clue.

**Comment by spicydonuts** [comment]
Should state selection be done after the async operation?  https://github.com/coot/redox-issue/blob/loading/src/App/Store.purs#L82
Seems like it could cache an old state and return that.

**Comment by spicydonuts** [comment]
I removed `bower_components` and `output` and rebuilt everything and it works great, no `delay` needed 🎉

**Comment by spicydonuts** [comment]
Somehow when I updated it knew enough to make me add `Eq` instances for my component state selectors but not the types in `App.Domain`.  Surprised it wasn't throwing any exceptions.

**Comment by spicydonuts** [comment]
One other note on that change, if a component is rendering a large list of things that contain a few nested types inside each item (some with their own lists of things), it seems like that `eq` call will be extremely expensive.  Since it's basically memoization, wouldn't a shallow `===` in FFI accomplish the same thing much faster?

**Comment by coot** [comment]
Yes. You can use `React.Redox.unsafeStrictEqual` which does exactly that.

**Comment by spicydonuts** [comment]
By overriding [this shouldCompontUpdate](https://github.com/coot/purescript-react-redox/blob/master/src/React/Redox.purs#L160) with a custom implementation?

**Comment by coot** [comment]
Not necessarily, in most cases it's enough to wrap the type in a `newtype` and give it a new `Eq` instance.
